server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://psyko460.fr:3306/ebt_transaction
    username: ebt
    password: ebt
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

application:
  sample:
    url: http://localhost:8085
    features:
      create: /sample/create